/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.autonoma.GuiLogo;

import co.edu.autonoma.classLogo.LectorinstruccionesTortuga;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class listaInstrucciones extends javax.swing.JDialog {
    DefaultTableModel list = new DefaultTableModel();
    private ArrayList<String> misComandos;
    /**
     * Creates new form listaInstrucciones
     */
    public listaInstrucciones(java.awt.Frame parent, boolean modal, ArrayList<String> comandos) {
        super(parent, modal);
        initComponents();
        this.misComandos = new ArrayList<>();
        this.misComandos = comandos;
        llenar();
    }

    public void llenar(){
        String nombresColumnas[] = {"Comando"};
        DefaultTableModel miModelo = new DefaultTableModel(null, nombresColumnas);
        this.tblComandos.setModel(miModelo);
        
        for (String comando : this.misComandos) {
                 
                    String fila[] = new String[nombresColumnas.length];
                    fila[0] = comando;
                    miModelo.addRow(fila);
    }
        
    }
    
//    public void crear(LectorinstruccionesTortuga lector){
//        tblComandos.addMouseListener(new MouseAdapter() {
//            public void mouseClicked(MouseEvent e) {
//                int filaSeleccionada = tblComandos.getSele();
//                if (filaSeleccionada != -1) { 
//                    Object dato1 = tblComandos.getValueAt(filaSeleccionada, 0);
//                    lector.runCommand((String) dato1);
//                }
//            }
//        });
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblComandos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblComandos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Comandos"
            }
        ));
        jScrollPane1.setViewportView(tblComandos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComandos;
    // End of variables declaration//GEN-END:variables
}
